### ISSUE TITLE
Avatars in Sample Chat App

### ISSUE THREAD

**Issue by jonknight73** [mosaicnetworks/babble-android#16]
The Message Object contains an instance of an Author object which has support for an Avatar. 

It would be a relatively minor enhancement to specify images in that Author object. Whilst the infrastructure to allow a user to set / amend their own avatar is probably more complex that we want for the sample app, adding a github style avatar generation from the hash of the moniker would be simpler and self-contained.

**Comment by jonknight73** [comment]
Issue raised to capture it as a possible enhancement rather to suggest imminent implementation,

**Comment by joneskm** [comment]
[Pull request](https://github.com/mosaicnetworks/babble-android/commit/944d095e7d41d7a1318c71a3bba48ae298911df7) implementing avatar accepted.
