### ISSUE TITLE
Cannot start Babble on certain devices

### ISSUE THREAD

**Issue by joneskm** [mosaicnetworks/babble-android#20]
Starting Babble fails with the message:

Cannot initialize engine: Cannot acquire directory lock on "/data/user/0/io.mosaicnetworks.sample/files/babble/io.mosaicnetworks.sample_9tJjG8g4A0Bq_ccc_/badger_db".  Another process is using this Badger database.: permission denied

Issue seems to occur on devices running Android 6 only. Error was reproduced on Samsung A3 running Android 6.0.1 and Samsung Galaxy s5 running 6.0.1

[This project](https://github.com/raedahgroup/dcrlibwallet/issues/56) seems to have the same issue. They observe:

"Log suggest that SELinux is blocking the flock call, and issue seems to be a known bug in android 6. [See this](https://grokbase.com/t/gg/android-ndk/163n1xwsd4/flock-2-and-selinux-permission-issuesl).

**Comment by jonknight73** [comment]
I have experienced the same issue on an Amazon Fire Tablet with a nominal API 22, Android 5.1.1.

**Comment by jonknight73** [comment]
The exact issue is this one:

https://github.com/dgraph-io/badger/issues/988

**Comment by joneskm** [comment]
This has been fixed in the [Babble](https://github.com/mosaicnetworks/babble) dependency by [this] (https://github.com/mosaicnetworks/babble/pull/140) pull request.
