### ISSUE TITLE
Can't see advertised groups on some devices

### ISSUE THREAD

**Issue by joneskm** [mosaicnetworks/babble-android#27]
On some devices the NsdServiceInfo.getAttributes() method returns an empty map. This map should contain the mDNS TXT record.

Error was reproduced on Samsung A3 running Android 6.0.1 and Samsung Galaxy s5 running 6.0.1

This is a known issue on pre Android 7 devices, [see this](https://issuetracker.google.com/issues/37020436), which according to the link, will not be fixed.

**Comment by jonknight73** [comment]
Fallback to use this?

https://github.com/youviewtv/tinydnssd

**Comment by jonknight73** [comment]
Fixing in issue-27 branch. 8c61ef927f6483cb75b7fce32b876ac9a1c7cddf

**Comment by joneskm** [comment]
[Pull request](https://github.com/mosaicnetworks/babble-android/commit/d45dd03e619877cc9037ef660ee313f38cf288ca) to fix issue accepted
